trigger:
  - main 

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'MyAzureSubscription'   
  appName: 'api-consultorio'   
  packageDirectory: '$(System.DefaultWorkingDirectory)'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build || echo "Nenhum build script definido, seguindo..."
  displayName: 'Install dependencies & Build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(packageDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(appName).zip'
    replaceExistingArchive: true
  displayName: 'Archive app'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '$(Build.ArtifactStagingDirectory)/$(appName).zip'
  displayName: 'Deploy to Azure Web App'
